☁️ chore(automation): Applying changes from upstream repository.

diff --git a/.config/taskfiles/ansible/Taskfile-test.yml b/.config/taskfiles/ansible/Taskfile-test.yml
--- a/.config/taskfiles/ansible/Taskfile-test.yml
+++ b/.config/taskfiles/ansible/Taskfile-test.yml
@@ -218,6 +218,15 @@ tasks:
       **Save test results for use with auto-generating compatibility chart:**
       `task ansible:test:molecule:docker:matrix`
     cmds:
+      - |
+        if ! docker run --rm hello-world; then
+        .config/log warn 'The command `docker run --rm hello-world` failed'
+          if [ -f '/Applications/Docker.app' ]; then
+            .config/log info 'Attempting to open `Applications/Docker.app` (Docker Desktop for macOS)'
+            open /Applications/Docker.app
+            sleep 30
+          fi
+        fi
       - task: molecule:docker:{{if .CLI_ARGS}}cli{{else}}prompt{{end}}
 
   molecule:docker:cli:
@@ -565,7 +574,7 @@ tasks:
     cmds:
       - task: molecule:virtualbox:{{if .CLI_ARGS}}cli{{else}}prompt{{end}}
 
-  # yYmllint disable rule:truthy
+  # yamllint disable rule:truthy
   molecule:virtualbox:cli:
     deps:
       - molecule:dependencies
@@ -678,6 +687,7 @@ tasks:
       - sh: test -f molecule/desktop/molecule.yml
         msg: The `molecule/desktop/molecule.yml` file must be present and in the proper format
 
+
   molecule:virtualbox:matrix:
     deps:
       - molecule:dependencies
@@ -702,7 +712,7 @@ tasks:
         vars:
           RESULTS_FILE: '{{.MOLECULE_LOGS_PATH}}/{{.MOLECULE_DATE}}-default.txt'
 
-  # yYmllint enable rule:truthy
+  # yamllint enable rule:truthy
   molecule:virtualbox:prompt:
     vars:
       MARKDOWN: |
